<?php

namespace App\Support;

use Workflow\V2\Support\PlatformConformanceSuite;

/**
 * Platform-level contract describing how a workflow in one namespace makes a
 * durable, retried, observable call into another namespace.
 *
 * The Nexus contract names: the wire surface (routes the durable cross-
 * namespace call rides), the addressing model (endpoint / service /
 * operation triple plus the caller / target namespace identities), the
 * operation modes (sync, async, sync-with-durable-reference), the durable
 * record (`workflow_service_calls` row that is the system of record for
 * every call), the lifecycle and outcome enumeration callers must handle,
 * the retry/durability semantics, the namespace-ACL enforcement points,
 * and the caller-side observability surface (the per-workflow Nexus
 * operation index that lets operators answer "what cross-namespace calls
 * has this workflow made?" without inspecting raw transport logs).
 *
 * Nexus is the parity name for the existing cross-namespace service layer
 * that landed under the workflow Phase TD-061 and the cross-namespace
 * service binding contract. Nothing in this contract introduces a parallel
 * primitive: it freezes the parity-named view of those primitives so SDKs
 * targeting the Temporal Nexus shape have a single, named surface to
 * implement.
 *
 * This is a stable consumer surface: changing the schema, removing
 * lifecycle values / outcomes, or removing routes is a breaking change
 * and requires a `version` bump.
 */
final class NexusContract
{
    public const SCHEMA = 'durable-workflow.v2.nexus.contract';

    public const VERSION = 2;

    public const RESULT_SCHEMA = 'durable-workflow.v2.nexus-runtime.result';

    public const RESULT_VERSION = 1;

    public const AUTHORITY_DOCUMENT = 'docs/contracts/nexus.md';

    public const UNDERLYING_EXECUTION_CONTRACT = 'durable-workflow.v2.service-execution.contract';

    /**
     * @return array<string, mixed>
     */
    public static function manifest(): array
    {
        return [
            'schema' => self::SCHEMA,
            'version' => self::VERSION,
            'authority_document' => self::AUTHORITY_DOCUMENT,
            'parity_target' => [
                'name' => 'Nexus',
                'description' => 'Durable workflow-to-workflow and service-to-service calls across namespace boundaries with activity-style retry, durability, and observability semantics.',
                'replaces_per_pair_integration' => true,
            ],
            'underlying_execution_contract' => self::UNDERLYING_EXECUTION_CONTRACT,
            'cluster_info_key' => 'nexus_contract',
            'capability_flag' => 'nexus',
            'platform_conformance_suite_authority' => PlatformConformanceSuite::SCHEMA,
            'result_schema' => self::RESULT_SCHEMA,
            'result_version' => self::RESULT_VERSION,
            'addressing' => [
                'endpoint_field' => 'endpoint_name',
                'service_field' => 'service_name',
                'operation_field' => 'operation_name',
                'caller_namespace_field' => 'caller_namespace',
                'target_namespace_field' => 'target_namespace',
                'caller_workflow_instance_field' => 'caller_workflow_instance_id',
                'caller_workflow_run_field' => 'caller_workflow_run_id',
                'idempotency_field' => 'idempotency_key',
                'durable_call_id_field' => 'service_call_id',
                'unknown_caller_namespace_policy' => 'fallback_to_request_namespace',
            ],
            'wire_surface' => [
                'register_endpoint' => 'POST /api/service-endpoints',
                'register_service' => 'POST /api/service-endpoints/{endpoint}/services',
                'register_operation' => 'POST /api/service-endpoints/{endpoint}/services/{service}/operations',
                'invoke_operation' => 'POST /api/service-endpoints/{endpoint}/services/{service}/operations/{operation}/execute',
                'describe_call' => 'GET /api/service-endpoints/{endpoint}/services/{service}/operations/{operation}/service-calls/{serviceCallId}',
                'cancel_call' => 'POST /api/service-endpoints/{endpoint}/services/{service}/operations/{operation}/service-calls/{serviceCallId}/cancel',
                'caller_history' => 'GET /api/workflows/{workflowId}/runs/{runId}/nexus-operations',
            ],
            'operation_modes' => ['sync', 'async', 'sync_with_durable_reference'],
            'lifecycle_statuses' => ['pending', 'accepted', 'started', 'completed', 'failed', 'cancelled'],
            'outcomes' => [
                'accepted',
                'completed',
                'cancelled',
                'timed_out',
                'rejected_not_found',
                'rejected_forbidden',
                'rejected_throttled',
                'rejected_concurrency_limited',
                'rejected_circuit_open',
                'degraded',
                'handler_failed',
            ],
            'handler_binding_kinds' => [
                'workflow_run',
                'workflow_update',
                'workflow_signal',
                'workflow_query',
                'activity_execution',
                'invocable_carrier_request',
            ],
            'retry_durability' => [
                'caller_recovery' => 'durable_record_keyed_by_service_call_id',
                'idempotent_resume' => 'caller_replays_with_same_idempotency_key',
                'retry_policy_source' => 'operation.retry_policy snapped onto the call row at admission',
                'retry_policy_shape' => 'activity_style',
                'crash_recovery' => 'caller_worker_resumes_by_service_call_id_after_restart',
                'history_recording' => 'every_admission_is_durable_before_handler_dispatch',
            ],
            'namespace_acl_enforcement' => [
                'principal_source' => 'authenticated_request_principal',
                'caller_namespace_source' => 'request_or_principal_resolved_namespace',
                'forging_caller_namespace' => 'rejected_forbidden_when_principal_disallows',
                'admission_gate' => 'App\\Support\\ServiceCallBoundary',
                'audit_trail' => 'workflow_service_calls.caller_principal_subject',
                'rejection_outcome' => 'rejected_forbidden',
                'enforcement_phase' => 'before_handler_dispatch',
            ],
            'multi_namespace_caller_pattern' => [
                'per_caller_registration_required' => false,
                'caller_namespaces_recorded_independently' => true,
                'fanout_supported' => true,
                'description' => 'A single Nexus service in target namespace B may be called by workflows in any caller namespace A1..An without per-caller registration. Each call records its own caller_namespace; the boundary gate evaluates each caller independently.',
            ],
            'caller_history_surface' => [
                'route' => 'GET /api/workflows/{workflowId}/runs/{runId}/nexus-operations',
                'description' => 'Caller-indexed view of every Nexus call this workflow run scheduled. Each row carries the durable service-call id, the resolved binding, the lifecycle status, the outcome, the linked target reference, the retry policy, per-attempt retry records, and the caller principal that admitted the call. Operators debugging a failed run answer "what cross-namespace calls did this workflow make and how did each attempt settle?" from this single surface.',
                'response_fields' => [
                    'service_call_id',
                    'caller_workflow_instance_id',
                    'caller_workflow_run_id',
                    'caller_namespace',
                    'target_namespace',
                    'endpoint_name',
                    'service_name',
                    'operation_name',
                    'operation_mode',
                    'status',
                    'outcome',
                    'outcome_category',
                    'outcome_reason',
                    'outcome_message',
                    'outcome_metadata',
                    'service_error_type',
                    'caller_observed_error_type',
                    'typed_error_message',
                    'resolved_binding_kind',
                    'resolved_target_reference',
                    'linked_workflow_instance_id',
                    'linked_workflow_run_id',
                    'linked_workflow_update_id',
                    'idempotency_key',
                    'retry_policy',
                    'service_call_attempts',
                    'retry_attempt_count',
                    'failure_message',
                    'caller_principal_subject',
                    'caller_principal_method',
                    'accepted_at',
                    'started_at',
                    'completed_at',
                    'failed_at',
                    'cancelled_at',
                ],
            ],
            'sdk_implementation_notes' => [
                'declare_operation' => 'SDKs MUST address operations through the endpoint / service / operation triple; the underlying handler binding is an internal resolution detail and MUST NOT be assumed by callers.',
                'operation_mode_default' => 'async',
                'sync_block_handling' => 'A sync caller still records a durable service-call id; the SDK MUST surface that id alongside the inline result so observers can recover the same call after the fact.',
                'idempotency_handling' => 'When the caller supplies an idempotency_key matching an existing in-flight or terminal call in the same target namespace + operation, the server MUST return the existing call rather than admitting a new one.',
                'retry_handling' => 'SDKs MUST treat the recorded retry_policy on the call row as authoritative; client-side retry logic MUST not duplicate calls when the server has already accepted them.',
                'observability_handling' => 'SDKs MUST expose the durable service-call id to user code so the caller workflow can record the id in its own observability surface (logs, search attributes, memos).',
            ],
            'out_of_scope' => [
                'general_service_mesh' => 'Nexus is durable cross-namespace calls within a durable-workflow cluster; it is not a generalized service mesh, sidecar fabric, or cross-cluster routing layer.',
                'arbitrary_external_http' => 'Nexus does not invoke arbitrary external HTTP endpoints; outbound HTTP belongs in the existing invocable-carrier surface.',
            ],
            'artifact_policy' => [
                'version_source' => 'latest_published_artifacts_at_run_time',
                'required_artifacts' => [
                    'server',
                    'cli',
                    'workflow',
                    'sdk-php',
                    'sdk-python',
                    'waterline',
                ],
                'release_artifact_aliases' => [
                    'workflow' => ['workflow-php'],
                    'sdk-python' => ['python-sdk'],
                ],
                'install_channels' => [
                    'server' => 'docker image durableworkflow/server:<exact tag or digest>',
                    'cli' => 'official dw GitHub release asset under durable-workflow/cli/releases/download/<exact tag>/',
                    'workflow' => 'Composer package durable-workflow/workflow:2.0.0-alpha.<exact>',
                    'sdk-php' => 'exact Composer package durable-workflow/sdk from Packagist',
                    'sdk-python' => 'PyPI package durable-workflow==<exact>',
                    'waterline' => 'Composer package durable-workflow/waterline:2.0.0-alpha.<exact>',
                ],
                'source_channel_policy' => [
                    'server' => 'docker://durableworkflow/server:<exact tag> or durableworkflow/server@sha256:<digest>',
                    'cli' => 'https://github.com/durable-workflow/cli/releases/download/<exact tag>/<release asset>',
                    'workflow' => 'packagist://durable-workflow/workflow@<exact version>',
                    'sdk-php' => 'packagist://durable-workflow/sdk@<exact version>',
                    'sdk-python' => 'pypi://durable-workflow==<exact version>',
                    'waterline' => 'packagist://durable-workflow/waterline@<exact version>',
                ],
                'forbidden_sources' => [
                    'local_product_source_checkout',
                    'workspace_repo_as_artifact_under_test',
                    'local_checkout_artifact',
                    'local_checkout',
                    'local_source_checkout',
                    'workspace_repo',
                    'rolling_server_image_tag',
                    'unverified_artifact_source',
                ],
                'placeholder_version_examples' => [
                    'latest',
                    'current',
                    'head',
                    'unresolved',
                    'placeholder',
                    '<latest>',
                    '1.x',
                    '${VERSION}',
                    '{{ version }}',
                ],
                'required_run_record_fields' => [
                    'artifact_versions',
                    'published_artifact_versions',
                    'resolved_artifact_versions',
                    'artifact_sources',
                    'artifact_source_verification',
                    'artifact_install_evidence',
                    'artifact_policy_failures',
                    'local_product_source_checkouts_used',
                    'started_at',
                    'finished_at',
                    'generated_at',
                    'outcome',
                    'scenario_results',
                    'findings',
                    'finding_links',
                ],
            ],
            'scenario_statuses' => [
                'pass',
                'fail',
                'unsupported',
                'not_covered',
                'runner_blocked',
            ],
            'required_matrix' => [
                'namespaces' => [
                    'tenant-a',
                    'tenant-b',
                    'shared',
                    'denied',
                ],
                'caller_runtimes' => [
                    'sdk-php',
                    'sdk-python',
                ],
                'service_runtimes' => [
                    'workflow-php',
                    'sdk-python',
                ],
                'required_operator_surfaces' => [
                    'caller_history',
                    'service_call_detail',
                    'waterline_operator_visibility',
                ],
            ],
            'required_scenarios' => [
                'published_artifact_install_only',
                'tenant_a_calls_shared_service',
                'tenant_b_calls_shared_service',
                'transient_failure_retries_with_policy',
                'permanent_failure_preserves_typed_error',
                'worker_restart_replay_does_not_reissue_call',
                'caller_cancellation_propagates_to_service',
                'php_caller_python_service',
                'python_caller_php_service',
                'endpoint_permission_denied_without_information_leak',
                'malformed_payload_refused_before_dispatch',
                'nonexistent_endpoint_typed_not_found',
                'caller_history_attempt_visibility',
                'result_record_and_product_finding_routing',
            ],
            'scenario_evidence_requirements' => [
                'published_artifact_install_only' => [
                    'artifact_versions',
                    'artifact_sources',
                    'artifact_source_verification',
                    'local_product_source_checkouts_used',
                    'install_channels_verified',
                    'artifact_install_evidence',
                ],
                'tenant_a_calls_shared_service' => [
                    'caller_namespace',
                    'target_namespace',
                    'endpoint_name',
                    'service_name',
                    'operation_name',
                    'service_call_id',
                    'workflow_result',
                    'request',
                    'response',
                    'service_call_record',
                    'caller_history_evidence',
                    'caller_history_recorded',
                ],
                'tenant_b_calls_shared_service' => [
                    'caller_namespace',
                    'target_namespace',
                    'endpoint_name',
                    'service_name',
                    'operation_name',
                    'service_call_id',
                    'workflow_result',
                    'request',
                    'response',
                    'service_call_record',
                    'caller_history_evidence',
                    'caller_history_recorded',
                ],
                'transient_failure_retries_with_policy' => [
                    'service_call_id',
                    'retry_policy',
                    'retry_attempts',
                    'history_attempt_visibility_includes_retry_attempts',
                    'completed_after_retry',
                ],
                'permanent_failure_preserves_typed_error' => [
                    'service_call_id',
                    'service_error_type',
                    'caller_observed_error_type',
                    'typed_error_preserved',
                ],
                'worker_restart_replay_does_not_reissue_call' => [
                    'service_call_id',
                    'published_artifact_worker_execution',
                    'issued_call_ids',
                    'caller_history_rows',
                    'service_logs',
                    'call_issued_at',
                    'caller_worker_stopped_at',
                    'caller_worker_restarted_at',
                    'call_completed_at',
                    'worker_restart_observed',
                    'history_replay_recovered_call',
                    'replay_transport',
                    'service_invocation_count',
                    'duplicate_call_assertion',
                    'duplicate_call_issue_count',
                ],
                'caller_cancellation_propagates_to_service' => [
                    'service_call_id',
                    'published_artifact_worker_execution',
                    'caller_history_rows',
                    'service_logs',
                    'caller_cancelled_at',
                    'target_cancelled_at',
                    'cancellation_propagation_ms',
                    'within_propagation_window',
                    'cancellation_type',
                    'typed_cancellation_observed',
                ],
                'php_caller_python_service' => [
                    'caller_workflow_instance_id',
                    'caller_workflow_run_id',
                    'caller_sdk_language',
                    'service_sdk_language',
                    'operation_name',
                    'request_payload',
                    'response_or_failure_surface',
                    'service_call_id',
                    'artifact_tuple',
                    'published_artifact_worker_execution',
                    'service_health',
                    'service_probe_succeeded',
                    'service_response_payload',
                    'payload_round_trip',
                    'typed_error_probe_succeeded',
                    'typed_error_round_trip',
                ],
                'python_caller_php_service' => [
                    'caller_workflow_instance_id',
                    'caller_workflow_run_id',
                    'caller_sdk_language',
                    'service_sdk_language',
                    'operation_name',
                    'request_payload',
                    'response_or_failure_surface',
                    'service_call_id',
                    'artifact_tuple',
                    'published_artifact_worker_execution',
                    'service_health',
                    'service_probe_succeeded',
                    'service_response_payload',
                    'payload_round_trip',
                    'typed_error_probe_succeeded',
                    'typed_error_round_trip',
                ],
                'endpoint_permission_denied_without_information_leak' => [
                    'caller_namespace',
                    'request',
                    'response',
                    'dispatch_evidence',
                    'caller_history_evidence',
                    'caller_history_query_succeeded',
                    'caller_history_state_proven',
                    'refusal_status',
                    'authorization_refusal_disclosed_endpoint_existence',
                    'handler_dispatch_count',
                    'service_invoked',
                ],
                'malformed_payload_refused_before_dispatch' => [
                    'request',
                    'response',
                    'dispatch_evidence',
                    'caller_history_evidence',
                    'caller_history_query_succeeded',
                    'caller_history_state_proven',
                    'refusal_status',
                    'typed_error',
                    'handler_dispatch_count',
                    'service_invoked',
                ],
                'nonexistent_endpoint_typed_not_found' => [
                    'request',
                    'response',
                    'dispatch_evidence',
                    'caller_history_evidence',
                    'caller_history_query_succeeded',
                    'caller_history_state_proven',
                    'refusal_status',
                    'typed_error',
                    'handler_dispatch_count',
                    'service_invoked',
                ],
                'caller_history_attempt_visibility' => [
                    'service_call_id',
                    'caller_history_attempts',
                    'history_attempt_visibility_includes_retry_attempts',
                    'service_call_detail_attempts',
                ],
                'result_record_and_product_finding_routing' => [
                    'result_record_emitted',
                    'finding_links_emitted',
                    'waterline_operator_visibility',
                ],
            ],
            'coverage_gate' => [
                'passing_outcome_requires' => [
                    'runner_blocked_false_for_product_evidence',
                    'published_artifact_versions_are_recorded_and_pinned',
                    'every_required_scenario_has_one_result',
                    'every_required_scenario_passes',
                    'each_pass_scenario_has_scenario_specific_evidence',
                    'each_non_pass_scenario_has_focused_linked_findings',
                    'no_local_product_source_checkout_used_as_artifact',
                ],
                'runner_blocked_outcome' => 'non_passing_runner_blocked',
                'coverage_gap_outcome' => 'non_passing_not_covered',
            ],
            'host_runner_contract' => [
                'status' => 'required_for_passing_nexus_conformance',
                'runner_path' => 'scripts/conformance/nexus-published-artifacts.sh',
                'runner_command' => 'scripts/conformance/nexus-published-artifacts.sh --result-dir <result-dir>',
                'result_files' => [
                    'pins.json',
                    'nexus-conformance-result.json',
                    'nexus-conformance-record.json',
                ],
                'must_execute_against_published_artifacts' => true,
                'must_record_runner_blocked_false_for_product_evidence' => true,
                'must_emit_result_for_every_required_scenario' => true,
                'required_execution_scopes' => [
                    'published-artifact-install',
                    'cross-namespace-happy-paths',
                    'retry-replay-and-cancellation',
                    'php-python-runtime-matrix',
                    'authorization-and-adversarial-refusals',
                    'history-and-result-record-routing',
                ],
                'evidence_inputs' => [
                    'DW_NEXUS_EVIDENCE_JSON' => 'Optional full host evidence document with scenario_results for the required Nexus scenarios. Missing scenarios are emitted as not_covered with focused conformance-harness findings.',
                    'DW_NEXUS_ARTIFACT_INSTALL_EVIDENCE' => 'Optional dedicated install-evidence JSON proving every required artifact came from a published install channel and no local product source checkout was used as the artifact under test.',
                    'DW_SERVER_VERSION' => 'Exact published server artifact version.',
                    'DW_CLI_VERSION' => 'Exact published CLI artifact version.',
                    'DW_WORKFLOW_PHP_VERSION' => 'Exact published Workflow PHP artifact version.',
                    'DW_PHP_SDK_VERSION' => 'Exact published durable-workflow/sdk artifact version.',
                    'DW_PYTHON_SDK_VERSION' => 'Exact published Python SDK artifact version.',
                    'DW_WATERLINE_VERSION' => 'Exact published Waterline artifact version.',
                    'DW_NEXUS_CONFORMANCE_RUN_ID' => 'Optional host conformance run id to copy into the Nexus result and ledger record.',
                ],
                'runtime_shards' => [
                    'sdk-php' => [
                        'artifact' => 'durable-workflow/sdk',
                        'must_cover_scenarios' => [
                            'php_caller_python_service',
                        ],
                    ],
                    'workflow-php' => [
                        'artifact' => 'durable-workflow/workflow',
                        'must_cover_scenarios' => [
                            'python_caller_php_service',
                            'caller_cancellation_propagates_to_service',
                            'worker_restart_replay_does_not_reissue_call',
                        ],
                    ],
                    'sdk-python' => [
                        'artifact' => 'durable-workflow',
                        'must_cover_scenarios' => [
                            'python_caller_php_service',
                            'permanent_failure_preserves_typed_error',
                        ],
                    ],
                    'server' => [
                        'artifact' => 'durableworkflow/server',
                        'must_cover_scenarios' => [
                            'tenant_a_calls_shared_service',
                            'tenant_b_calls_shared_service',
                            'transient_failure_retries_with_policy',
                            'worker_restart_replay_does_not_reissue_call',
                            'caller_cancellation_propagates_to_service',
                            'endpoint_permission_denied_without_information_leak',
                            'malformed_payload_refused_before_dispatch',
                            'nonexistent_endpoint_typed_not_found',
                            'caller_history_attempt_visibility',
                        ],
                    ],
                    'waterline' => [
                        'artifact' => 'durable-workflow/waterline',
                        'must_cover_scenarios' => [
                            'caller_history_attempt_visibility',
                            'result_record_and_product_finding_routing',
                        ],
                    ],
                ],
                'routing_policy' => [
                    'missing_required_scenario' => [
                        'scenario_status' => 'not_covered',
                        'finding_type' => 'conformance_runner_coverage_gap',
                        'owner' => 'conformance_harness',
                    ],
                    'host_environment_failure' => [
                        'scenario_status' => 'runner_blocked',
                        'finding_type' => 'runner_gap',
                        'owner' => 'conformance_harness',
                    ],
                    'unsupported_public_surface' => [
                        'scenario_status' => 'unsupported',
                        'finding_source' => 'nexus_contract.finding_policy',
                    ],
                    'product_behavior_failure' => [
                        'scenario_status' => 'fail',
                        'finding_source' => 'nexus_contract.finding_policy',
                    ],
                ],
            ],
            'result_gate' => [
                'schema' => self::RESULT_SCHEMA.'.gate',
                'version' => self::RESULT_VERSION,
                'pass_requires' => [
                    'runner_blocked_false_for_product_evidence',
                    'published_artifact_versions_are_recorded_and_pinned',
                    'all_required_artifact_versions_are_concrete',
                    'artifact_sources_recorded_for_every_required_artifact',
                    'artifact_source_verification_proves_each_source_resolves',
                    'published_artifact_install_evidence_reported',
                    'install_artifact_tuple_matches_top_level_resolved_tuple',
                    'no_artifact_policy_failures',
                    'every_required_scenario_has_one_result',
                    'every_required_scenario_passes',
                    'each_pass_scenario_has_scenario_specific_evidence',
                    'each_non_pass_scenario_has_focused_linked_findings',
                    'local_product_source_checkouts_used_false',
                    'source_free_published_artifact_evidence_is_explicit',
                    'shared_service_tenant_cells_attach_request_response_service_call_and_history',
                    'replay_and_cancellation_cells_attach_published_worker_execution',
                    'php_python_service_shards_return_valid_health',
                    'history_attempt_visibility_includes_retry_attempts',
                    'authorization_refusal_does_not_disclose_endpoint_existence',
                ],
                'artifact_version_policy' => [
                    'rejects_placeholder_versions' => true,
                    'requires_required_artifacts' => [
                        'server',
                        'cli',
                        'workflow',
                        'sdk-php',
                        'sdk-python',
                        'waterline',
                    ],
                    'placeholder_tokens' => [
                        'latest',
                        'current',
                        'head',
                        'unresolved',
                        'placeholder',
                        '<latest>',
                        '1.x',
                        '${VERSION}',
                        '{{ version }}',
                    ],
                    'local_product_source_checkouts_used_must_be_false' => true,
                    'requires_artifact_sources_for_required_artifacts' => true,
                    'requires_downloadable_artifact_source_verification' => true,
                    'requires_explicit_source_free_evidence' => true,
                ],
            ],
            'finding_policy' => [
                'root_cause_owners' => [
                    'retry_does_not_happen' => 'server',
                    'retry_attempt_visibility_gap' => 'server',
                    'worker_restart_reissues_call' => 'server_or_sdk',
                    'typed_error_shape_loss' => 'codec_or_worker_protocol',
                    'cancellation_does_not_propagate' => 'server',
                    'permission_denied_information_leak' => 'server',
                    'cross_language_call_failure' => 'server_or_sdk',
                    'operator_visibility_gap' => 'waterline_or_server',
                    'published_artifact_handoff_gap' => 'owning_release_surface',
                    'missing_or_invalid_published_nexus_artifact' => 'owning_release_surface',
                    'local_product_source_checkout_used' => 'conformance_harness',
                    'conformance_runner_coverage_gap' => 'conformance_harness',
                ],
                'required_for_non_pass' => [
                    'scenario_id',
                    'owning_surface',
                    'artifact_versions',
                    'observed_behavior',
                    'expected_behavior',
                    'next_acceptance_criterion',
                ],
            ],
        ];
    }
}
