{{- if .Values.bootstrap.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "durable-workflow.bootstrapJobName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "durable-workflow.componentLabels" (dict "context" . "component" "migration") | nindent 4 }}
  annotations:
    {{- if .Values.bootstrap.useHelmHooks }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- end }}
    {{- include "durable-workflow.argoBootstrapAnnotations" . | nindent 4 }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: {{ .Values.bootstrap.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.bootstrap.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "durable-workflow.componentLabels" (dict "context" . "component" "migration") | nindent 8 }}
        {{- with .Values.bootstrap.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.bootstrap.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "durable-workflow.bootstrapServiceAccountName" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.bootstrap.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrate
          image: {{ include "durable-workflow.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["server-entrypoint"]
          args:
            {{- toYaml .Values.bootstrap.args | nindent 12 }}
          {{- with (include "durable-workflow.bootstrapEnvFrom" . | trim) }}
          envFrom:
            {{- . | nindent 12 }}
          {{- end }}
          env:
            {{- include "durable-workflow.bootstrapEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.bootstrap.resources | nindent 12 }}
          {{- with .Values.bootstrap.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.bootstrap.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bootstrap.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bootstrap.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
