// Generated by scripts/generate-voiceover.ts — do not edit by hand.
export const SCENE_AUDIO_FRAMES = [138, 271, 396, 303, 492, 271] as const;
export const SCENE_FROM_FRAMES = [0, 138, 409, 805, 1108, 1600] as const;
export const LAUNCH_VIDEO_TOTAL_FRAMES = 1871 as const;
