import { execFileSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { elevenLabsTranscriptToCaptions } from "@remotion/elevenlabs";
import type { Caption } from "@remotion/captions";
import { ElevenLabsClient } from "@elevenlabs/elevenlabs-js";

const FPS = 30;

const SEGMENTS: { id: string; text: string }[] = [
  {
    id: "01-logo",
    text: "Get design. Turn any public URL into a design system.",
  },
  {
    id: "02-what-is-it",
    text: "Drop in a real site. Get design opens a live browser, reads the page's CSS, and turns it into a polished design dot em dee.",
  },
  {
    id: "03-how-it-works",
    text: "Point it at Stripe, Linear, or your own product. The agent crawls markup and styles, captures the page in a sandboxed browser, extracts tokens, and streams back a living design spec.",
  },
  {
    id: "04-deliverables",
    text: "You get more than a screenshot: palette, type, spacing, components, motion, responsive rules, and a prompt guide your team can actually build from.",
  },
  {
    id: "05-architecture",
    text: "Under the hood, one coordinator fans out to crawl, visual capture, token extraction, and synthesis. Convex keeps the run state, while web, API, CLI, SDK, and the IDE skill all share the same core.",
  },
  {
    id: "06-finale",
    text: "Get the design system for any URL. Visit get design dot app, or run en pee ex at get design slash CLI on your favorite site.",
  },
];

/** Safety cap per scene (frames); raise if copy is very long. */
const SCENE_MAX_FRAMES = 900;

function requireBin(name: string): void {
  try {
    execFileSync(name, ["-version"], { stdio: "pipe" });
  } catch {
    console.error(
      `Missing ${name} on PATH. Install ffmpeg (includes ffprobe) on your PATH.`,
    );
    process.exit(1);
  }
}

function probeDurationSeconds(path: string): number {
  const out = execFileSync(
    "ffprobe",
    [
      "-v",
      "error",
      "-show_entries",
      "format=duration",
      "-of",
      "default=noprint_wrappers=1:nokey=1",
      path,
    ],
    { encoding: "utf-8" },
  ).trim();
  const n = Number(out);
  if (!Number.isFinite(n)) {
    throw new Error(`ffprobe returned invalid duration for ${path}: ${out}`);
  }
  return n;
}

/** Whole-frame count that fully contains `durationSec` at `fps` (never shorter than audio). */
function durationToFrames(durationSec: number, fps: number): number {
  let frames = Math.max(1, Math.ceil(durationSec * fps - 1e-9));
  while (frames / fps < durationSec - 1e-6) {
    frames += 1;
  }
  return frames;
}

/**
 * Re-encode to MP3 and pad with silence so the file length is exactly `outSec`
 * (snap to whole frames). Does not trim: if decoder reports longer than outSec,
 * ffprobe after write drives the exported frame count.
 */
function encodeAndPadToSeconds(
  inputPath: string,
  outputPath: string,
  outSec: number,
): void {
  execFileSync(
    "ffmpeg",
    [
      "-y",
      "-i",
      inputPath,
      "-af",
      `apad=whole_dur=${outSec}`,
      "-c:a",
      "libmp3lame",
      "-b:a",
      "128k",
      outputPath,
    ],
    { stdio: "inherit" },
  );
}

function offsetCaptions(captions: Caption[], sceneStartMs: number): Caption[] {
  return captions.map((c) => ({
    ...c,
    startMs: c.startMs + sceneStartMs,
    endMs: c.endMs + sceneStartMs,
    timestampMs:
      c.timestampMs != null ? c.timestampMs + sceneStartMs : null,
  }));
}

async function transcribeMp3ToCaptions(
  apiKey: string,
  mp3Path: string,
  filename: string,
): Promise<Caption[]> {
  const buf = await readFile(mp3Path);
  const form = new FormData();
  form.append("file", new Blob([buf], { type: "audio/mpeg" }), filename);
  form.append("model_id", "scribe_v2");
  form.append("timestamps_granularity", "word");

  const res = await fetch("https://api.elevenlabs.io/v1/speech-to-text", {
    method: "POST",
    headers: { "xi-api-key": apiKey },
    body: form,
  });

  if (!res.ok) {
    const detail = await res.text();
    throw new Error(`speech-to-text ${res.status}: ${detail}`);
  }

  const transcript = await res.json();
  const { captions } = elevenLabsTranscriptToCaptions({ transcript });
  return captions;
}

async function writeGeneratedVoiceover(
  root: string,
  sceneFrames: number[],
): Promise<void> {
  const fromFrames: number[] = [];
  let acc = 0;
  for (let i = 0; i < sceneFrames.length; i++) {
    fromFrames.push(acc);
    acc += sceneFrames[i]!;
  }
  const total = acc;
  const path = join(root, "src", "generated-voiceover.ts");
  await writeFile(
    path,
    `// Generated by scripts/generate-voiceover.ts — do not edit by hand.\n` +
      `export const SCENE_AUDIO_FRAMES = [${sceneFrames.join(", ")}] as const;\n` +
      `export const SCENE_FROM_FRAMES = [${fromFrames.join(", ")}] as const;\n` +
      `export const LAUNCH_VIDEO_TOTAL_FRAMES = ${total} as const;\n`,
  );
  console.log(
    `Wrote ${path} (${sceneFrames.length} scenes, ${total}f total @ ${FPS}fps)`,
  );
}

async function main(): Promise<void> {
  const apiKey = process.env.ELEVENLABS_API_KEY;
  const voiceId = process.env.ELEVENLABS_VOICE_ID;
  if (!apiKey) {
    console.error("Set ELEVENLABS_API_KEY (e.g. in apps/video/.env).");
    process.exit(1);
  }
  if (!voiceId) {
    console.error("Set ELEVENLABS_VOICE_ID (e.g. in apps/video/.env).");
    process.exit(1);
  }

  requireBin("ffmpeg");
  requireBin("ffprobe");

  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const outDir = join(root, "public", "voiceover", "launch");
  await mkdir(outDir, { recursive: true });

  const client = new ElevenLabsClient({ apiKey });
  const tmpBase = await mkdtemp(join(tmpdir(), "getdesign-vo-"));

  const sceneFrames: number[] = [];
  const allCaptions: Caption[] = [];
  let sceneStartFrames = 0;

  try {
    for (const seg of SEGMENTS) {
      const rawPath = join(tmpBase, `${seg.id}-raw.mp3`);
      const finalPath = join(outDir, `${seg.id}.mp3`);
      const sceneStartMs = (sceneStartFrames / FPS) * 1000;

      const stream = await client.textToSpeech.convert(voiceId, {
        text: seg.text,
        modelId: "eleven_multilingual_v2",
        outputFormat: "mp3_44100_128",
        voiceSettings: {
          stability: 0.46,
          similarityBoost: 0.75,
          style: 0.32,
        },
      });

      const chunks: Uint8Array[] = [];
      for await (const chunk of stream) {
        chunks.push(chunk);
      }
      await writeFile(rawPath, Buffer.concat(chunks));

      const rawDur = probeDurationSeconds(rawPath);
      let frames = durationToFrames(rawDur, FPS);
      if (frames > SCENE_MAX_FRAMES) {
        console.warn(
          `${seg.id}: ${frames}f exceeds SCENE_MAX_FRAMES (${SCENE_MAX_FRAMES}); trimming. Shorten copy or raise cap.`,
        );
        frames = SCENE_MAX_FRAMES;
      }
      const outSec = frames / FPS;
      console.log(
        `${seg.id}: raw ${rawDur.toFixed(3)}s → ${frames}f (${outSec.toFixed(3)}s, pad-only to frame)`,
      );

      encodeAndPadToSeconds(rawPath, finalPath, outSec);

      const finalDur = probeDurationSeconds(finalPath);
      const verified = durationToFrames(finalDur, FPS);
      sceneFrames.push(verified);

      try {
        const local = await transcribeMp3ToCaptions(
          apiKey,
          finalPath,
          `${seg.id}.mp3`,
        );
        allCaptions.push(...offsetCaptions(local, sceneStartMs));
        console.log(`${seg.id}: captions ${local.length} words`);
      } catch (e) {
        console.warn(`${seg.id}: speech-to-text failed (captions skipped):`, e);
      }

      sceneStartFrames += verified;
    }
  } finally {
    await rm(tmpBase, { recursive: true, force: true });
  }

  await writeFile(
    join(outDir, "captions.json"),
    `${JSON.stringify(allCaptions)}\n`,
    "utf-8",
  );
  console.log(
    `Wrote ${allCaptions.length} caption tokens → ${join(outDir, "captions.json")}`,
  );

  await writeGeneratedVoiceover(root, sceneFrames);

  console.log(`Wrote ${SEGMENTS.length} files to ${outDir}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
