---
name: CodSpeed

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    env:
      PYTHONHASHSEED: "0"
      # https://sourceware.org/glibc/manual/latest/html_node/Hardware-Capability-Tunables.html
      GLIBC_TUNABLES: "glibc.cpu.hwcaps=-AVX512F,-AVX512VL,-AVX512BW,-ERMS,-FSRM"

    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: "3.14"
          enable-cache: true

      - name: Install dependencies
        run: scripts/install
        shell: bash

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@0ca9cbbf4623b599a6c3ed4fc8a922942705d9f1 # v5.0.2
        with:
          run: >-
            uv run pytest
            benchmarks/gzip_benchmark.py
            benchmarks/multipart_benchmark.py
            benchmarks/request_benchmark.py
            benchmarks/response_benchmark.py
            benchmarks/routing_benchmark.py
            benchmarks/json_benchmark.py
            benchmarks/file_response_benchmark.py
            benchmarks/streaming_response_benchmark.py
            benchmarks/urlencoded_benchmark.py
            benchmarks/websocket_benchmark.py
            --codspeed
          mode: simulation,memory
