<?php

namespace App\Support;

use Workflow\V2\Support\PlatformConformanceSuite;

/**
 * Machine-readable contract for the live signals/queries conformance run.
 *
 * The platform conformance suite owns the category and scenario list. This
 * server-owned manifest expands that into the result fields, matrix axes,
 * gate behavior, and finding routing a runner needs to prove the category
 * without treating the Python smoke subset as complete coverage.
 */
final class SignalQueryRuntimeContract
{
    public const SCHEMA = 'durable-workflow.v2.signal-query-runtime.contract';

    public const VERSION = 39;

    public const RESULT_SCHEMA = 'durable-workflow.v2.signal-query-runtime.result';

    public const RESULT_VERSION = 1;

    /**
     * @return array<string, mixed>
     */
    public static function manifest(): array
    {
        return [
            'schema' => self::SCHEMA,
            'version' => self::VERSION,
            'result_schema' => self::RESULT_SCHEMA,
            'result_version' => self::RESULT_VERSION,
            'fixture_category' => 'signal_query_runtime_contract',
            'platform_conformance_suite_authority' => PlatformConformanceSuite::SCHEMA,
            'scenario_manifest' => [
                'schema' => 'durable-workflow.v2.platform-conformance.runtime-scenarios',
                'category' => 'signal_query_runtime_contract',
                'suite_version' => PlatformConformanceSuite::VERSION,
                'public_path' => 'https://durable-workflow.github.io/platform-conformance/signal-query-runtime-scenarios.json',
                'source_path' => 'static/platform-conformance/signal-query-runtime-scenarios.json',
            ],
            'artifact_policy' => [
                'version_source' => 'latest_published_artifacts_at_run_time',
                'version_requirement' => 'concrete_published_versions_pinned_at_run_time',
                'placeholder_versions_rejected' => true,
                'placeholder_version_examples' => [
                    'latest',
                    'current',
                    'head',
                    'unresolved',
                    'placeholder',
                    '<latest>',
                    '${VERSION}',
                    '{{ version }}',
                ],
                'install_channels' => [
                    'server' => 'docker image durableworkflow/server:<latest>',
                    'cli' => 'official dw install script pinned to its latest release tag',
                    'sdk-php' => 'Composer package durable-workflow/sdk:<latest>',
                    'sdk-python' => 'PyPI package durable-workflow==<latest>',
                    'sdk-rust' => 'crates.io package durable-workflow pinned with an exact Cargo requirement',
                    'workflow' => 'Composer package durable-workflow/workflow:2.0.0-alpha.<latest> for the embedded Laravel engine used by Waterline',
                    'waterline' => 'published Waterline Composer package and digest-pinned service image matching the latest release tag',
                ],
                'required_distribution_identities' => [
                    'workflow' => [
                        'version_component' => 'workflow',
                        'kind' => 'composer',
                        'package' => 'durable-workflow/workflow',
                    ],
                    'waterline' => [
                        'version_component' => 'waterline',
                        'kind' => 'composer',
                        'package' => 'durable-workflow/waterline',
                    ],
                    'waterline-service' => [
                        'version_component' => 'waterline',
                        'kind' => 'oci',
                        'package' => 'docker.io/durableworkflow/waterline',
                    ],
                    'server' => [
                        'version_component' => 'server',
                        'kind' => 'oci',
                        'package' => 'docker.io/durableworkflow/server',
                    ],
                    'cli' => [
                        'version_component' => 'cli',
                        'kind' => 'github-release',
                        'package' => 'durable-workflow/cli',
                    ],
                    'sdk-php' => [
                        'version_component' => 'sdk-php',
                        'kind' => 'composer',
                        'package' => 'durable-workflow/sdk',
                    ],
                    'sdk-python' => [
                        'version_component' => 'sdk-python',
                        'kind' => 'pypi',
                        'package' => 'durable-workflow',
                    ],
                    'sdk-rust' => [
                        'version_component' => 'sdk-rust',
                        'kind' => 'crates.io',
                        'package' => 'durable-workflow',
                    ],
                ],
                'install_proof_artifacts' => [
                    'server',
                    'cli',
                    'sdk-php',
                    'sdk-python',
                    'sdk-rust',
                ],
                'expected_sources' => [
                    'server' => 'published_docker_image',
                    'cli' => 'published_cli_release',
                    'sdk-php' => 'published_composer_package',
                    'sdk-python' => 'published_pypi_package',
                    'sdk-rust' => 'published_crates_io_package',
                    'workflow' => 'published_composer_package',
                    'waterline' => 'published_waterline_artifact',
                ],
                'forbidden_sources' => [
                    'local_product_source_checkout',
                    'workspace_repo_as_artifact_under_test',
                ],
                'required_run_record_fields' => [
                    'artifact_versions',
                    'started_at',
                    'finished_at',
                    'outcome',
                    'scenario_results',
                    'findings',
                    'finding_links',
                    'executed_distribution_identities',
                ],
            ],
            'scenario_statuses' => [
                'pass',
                'fail',
                'unsupported',
                'not_covered',
                'runner_blocked',
            ],
            'topology' => [
                'workflow_type' => 'Counter',
                'required_workers' => [
                    'sdk-php',
                    'sdk-python',
                    'sdk-rust',
                ],
                'required_handlers' => [
                    'signals' => [
                        'increment' => [
                            'arguments' => ['n:int'],
                            'effect' => 'adds n to the in-workflow counter',
                        ],
                        'set' => [
                            'arguments' => ['value:int'],
                            'effect' => 'overwrites the in-workflow counter',
                        ],
                    ],
                    'queries' => [
                        'current' => [
                            'returns' => 'int',
                            'effect' => 'reads the replayed counter state without mutation',
                        ],
                    ],
                ],
            ],
            'required_matrix' => [
                'runtimes' => [
                    'sdk-php',
                    'sdk-python',
                    'sdk-rust',
                ],
                'client_paths' => [
                    'cli',
                    'sdk-php',
                    'sdk-python',
                    'sdk-rust',
                ],
                'observer_paths' => [
                    'waterline-selected-run-detail',
                    'waterline-query-action',
                    'waterline-service-selected-run-detail',
                    'waterline-service-query-action',
                    'waterline-service-signal-action',
                ],
                'same_language_cells' => [
                    [
                        'worker' => 'sdk-python',
                        'clients' => ['cli', 'sdk-python'],
                        'scenario' => 'python_worker_cli_and_sdk_baseline',
                    ],
                    [
                        'worker' => 'sdk-php',
                        'clients' => ['cli', 'sdk-php'],
                        'scenario' => 'php_worker_cli_and_sdk_baseline',
                    ],
                    [
                        'worker' => 'sdk-rust',
                        'clients' => ['sdk-rust', 'sdk-php', 'sdk-python'],
                        'scenario' => 'rust_worker_rust_php_python_clients',
                    ],
                ],
                'cross_language_cells' => [
                    [
                        'worker' => 'sdk-python',
                        'clients' => ['sdk-php', 'cli'],
                        'scenario' => 'python_worker_php_facing_and_cli_clients',
                    ],
                    [
                        'worker' => 'sdk-php',
                        'clients' => ['sdk-python', 'cli'],
                        'scenario' => 'php_worker_python_and_cli_clients',
                    ],
                    [
                        'worker' => 'sdk-python',
                        'clients' => ['sdk-rust'],
                        'scenario' => 'python_worker_rust_client',
                    ],
                    [
                        'worker' => 'sdk-php',
                        'clients' => ['sdk-rust'],
                        'scenario' => 'php_worker_rust_client',
                    ],
                ],
            ],
            'required_scenarios' => [
                'published_artifact_install_only',
                'python_worker_cli_and_sdk_baseline',
                'php_worker_cli_and_sdk_baseline',
                'python_worker_php_facing_and_cli_clients',
                'php_worker_python_and_cli_clients',
                'rust_worker_rust_php_python_clients',
                'python_worker_rust_client',
                'php_worker_rust_client',
                'rust_query_error_and_immutability',
                'ordered_signal_delivery',
                'dedup_contract_observation',
                'signal_during_replay',
                'query_during_replay',
                'rust_replayed_instance_state_query_after_cold_restart',
                'completed_run_signal_and_query',
                'unknown_signal_and_query_errors',
                'malformed_signal_and_query_payloads',
                'waterline_operator_visibility',
                'waterline_service_operator_visibility',
            ],
            'scenario_requirements' => [
                'published_artifact_install_only' => [
                    'evidence' => [
                        'published_artifact_versions',
                        'artifact_sources',
                        'artifact_install_evidence',
                    ],
                ],
                'python_worker_cli_and_sdk_baseline' => [
                    'evidence' => [
                        'worker_runtime',
                        'python_worker_artifact_source',
                        'python_worker_sdk_version',
                        'python_worker_query_task_routing',
                        'routed_current_query_task',
                        'cli_signal_and_query',
                        'sdk_python_signal_and_query',
                        'immediate_repeat_query_consistency',
                        'readiness_boundary',
                        'controlled_restart',
                    ],
                ],
                'php_worker_cli_and_sdk_baseline' => [
                    'evidence' => [
                        'worker_runtime',
                        'sdk_php_artifact_source',
                        'sdk_php_sdk_version',
                        'php_worker_query_task_routing',
                        'cli_signal_and_query',
                        'sdk_php_signal_and_query',
                        'immediate_repeat_query_consistency',
                    ],
                ],
                'python_worker_php_facing_and_cli_clients' => [
                    'evidence' => [
                        'php_client_signal_and_query',
                        'cli_signal_and_query',
                        'cross_language_query_consistency',
                        'wire_envelope_compatibility',
                    ],
                ],
                'php_worker_python_and_cli_clients' => [
                    'evidence' => [
                        'sdk_python_signal_and_query',
                        'cli_signal_and_query',
                        'cross_language_query_consistency',
                        'wire_envelope_compatibility',
                    ],
                ],
                'rust_worker_rust_php_python_clients' => [
                    'query_state_model' => 'snapshot_derived_transport_state',
                    'evidence' => [
                        'worker_runtime',
                        'rust_sdk_version',
                        'rust_worker_registration.sdk_version',
                        'rust_crate_provenance.source',
                        'rust_crate_provenance.checksum',
                        'rust_crate_provenance.resolved_version',
                        'apache_avro_provenance.source',
                        'apache_avro_provenance.checksum',
                        'query_state_model',
                        'ordered_signal_values',
                        'rust_query_results.running',
                        'sdk_php_query_results.running',
                        'sdk_python_query_results.running',
                        'rust_query_results.completed',
                        'sdk_php_query_results.completed',
                        'sdk_python_query_results.completed',
                        'valid_avro_signal_and_query.default_codec',
                        'valid_avro_signal_and_query.payload_codec',
                        'valid_avro_signal_and_query.observed_value',
                        'repeat_query_consistency',
                    ],
                ],
                'python_worker_rust_client' => [
                    'evidence' => [
                        'worker_runtime',
                        'rust_sdk_version',
                        'rust_crate_provenance.source',
                        'rust_crate_provenance.resolved_version',
                        'rust_crate_provenance.checksum',
                        'ordered_signal_values',
                        'default_codec',
                        'payload_codec',
                        'rust_query_results',
                        'repeat_query_consistency',
                    ],
                ],
                'php_worker_rust_client' => [
                    'evidence' => [
                        'worker_runtime',
                        'rust_sdk_version',
                        'rust_crate_provenance.source',
                        'rust_crate_provenance.resolved_version',
                        'rust_crate_provenance.checksum',
                        'ordered_signal_values',
                        'default_codec',
                        'payload_codec',
                        'rust_query_results',
                        'rust_query_observed_values',
                        'prefix_consistent_query_results',
                        'query_result_rollback_free',
                        'repeat_query_consistency',
                    ],
                ],
                'rust_query_error_and_immutability' => [
                    'query_state_model' => 'snapshot_derived_transport_state',
                    'allowed_reasons' => [
                        'unknown_query' => ['rejected_unknown_query'],
                        'malformed_query_payload' => ['query_payload_decode_failed'],
                        'unavailable_query_handler' => ['query_handler_unavailable'],
                        'incompatible_query_protocol' => ['unsupported_protocol_version'],
                        'missing_workflow' => ['instance_not_found'],
                        'terminal_signal' => ['run_not_active'],
                    ],
                    'evidence' => [
                        'rust_sdk_version',
                        'rust_crate_provenance.source',
                        'rust_crate_provenance.resolved_version',
                        'rust_crate_provenance.checksum',
                        'query_state_model',
                        'unknown_query.reason',
                        'malformed_query_payload.reason',
                        'unavailable_query_handler.reason',
                        'incompatible_query_protocol.reason',
                        'missing_workflow.reason',
                        'terminal_signal.reason',
                        'terminal_signal.rejection_reason',
                        'history_and_commands_before_first_successful_query.history_event_count',
                        'history_and_commands_before_first_successful_query.workflow_command_count',
                        'history_and_commands_after_successful_queries.history_event_count',
                        'history_and_commands_after_successful_queries.workflow_command_count',
                        'history_and_commands_after_failure_queries.history_event_count',
                        'history_and_commands_after_failure_queries.workflow_command_count',
                        'successful_queries_appended_no_history',
                        'successful_queries_emitted_no_workflow_commands',
                        'failed_queries_appended_no_history',
                        'failed_queries_emitted_no_workflow_commands',
                        'answer_before_failures',
                        'answer_after_failures',
                        'failed_query_did_not_change_later_answer',
                    ],
                ],
                'ordered_signal_delivery' => [
                    'evidence' => [
                        'workflow_id',
                        'run_id',
                        'rapid_increment_inputs',
                        'accepted_signal_inputs',
                        'accepted_signal_total',
                        'queried_total',
                        'history_signal_order',
                        'final_run_status',
                        'ordered_query_responder',
                    ],
                    'expected_rapid_increment_inputs' => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                ],
                'dedup_contract_observation' => [
                    'evidence' => [
                        'client_side_key_support',
                        'documented_contract',
                        'handler_observation_count',
                    ],
                ],
                'signal_during_replay' => [
                    'required_behavior' => 'signal_applies_after_replay_consistent_point',
                    'evidence' => [
                        'signal_api_sample',
                        'signal_status_code',
                        'worker_restart_at',
                        'signal_sent_at',
                        'replay_completed_at',
                        'signal_applied_at',
                    ],
                    'timestamp_order' => [
                        'worker_restart_at <= signal_sent_at',
                        'signal_sent_at < replay_completed_at',
                        'replay_completed_at <= signal_applied_at',
                    ],
                ],
                'query_during_replay' => [
                    'required_behavior' => 'query_waits_for_replay_consistency',
                    'evidence' => [
                        'query_api_sample',
                        'query_status_code',
                        'worker_restart_at',
                        'query_sent_at',
                        'query_poll_started_at',
                        'replay_completed_at',
                        'query_handler_invoked_at',
                        'query_completed_at',
                        'query_answer',
                        'expected_answer',
                    ],
                    'timestamp_order' => [
                        'worker_restart_at <= query_sent_at',
                        'query_sent_at <= query_poll_started_at',
                        'query_poll_started_at < replay_completed_at',
                        'replay_completed_at <= query_handler_invoked_at',
                        'query_handler_invoked_at <= query_completed_at',
                    ],
                ],
                'rust_replayed_instance_state_query_after_cold_restart' => [
                    'query_state_model' => 'replayed_workflow_instance_state',
                    'failed_query_allowed_reasons' => ['rejected_unknown_query'],
                    'evidence' => [
                        'worker_runtime',
                        'rust_sdk_version',
                        'rust_crate_provenance.source',
                        'rust_crate_provenance.resolved_version',
                        'rust_crate_provenance.checksum',
                        'query_state_model',
                        'initial_worker_process_id',
                        'cold_restart.fresh_worker_process_id',
                        'cold_restart.durable_history_restored',
                        'running_query_results.sdk_rust',
                        'running_query_results.sdk_php_sdk',
                        'running_query_results.sdk_python',
                        'restored_query_results.sdk_rust',
                        'restored_query_results.sdk_php_sdk',
                        'restored_query_results.sdk_python',
                        'completed_query_results.sdk_rust',
                        'completed_query_results.sdk_php_sdk',
                        'completed_query_results.sdk_python',
                        'immutability_checkpoints.running.before_first_successful_query.history_event_count',
                        'immutability_checkpoints.running.before_first_successful_query.workflow_command_count',
                        'immutability_checkpoints.running.answer_before_failed_query',
                        'immutability_checkpoints.running.failed_query.reason',
                        'immutability_checkpoints.running.answer_after_failed_query',
                        'immutability_checkpoints.running.after_successful_and_failed_queries.history_event_count',
                        'immutability_checkpoints.running.after_successful_and_failed_queries.workflow_command_count',
                        'immutability_checkpoints.cold_restarted.before_first_successful_query.history_event_count',
                        'immutability_checkpoints.cold_restarted.before_first_successful_query.workflow_command_count',
                        'immutability_checkpoints.cold_restarted.answer_before_failed_query',
                        'immutability_checkpoints.cold_restarted.failed_query.reason',
                        'immutability_checkpoints.cold_restarted.answer_after_failed_query',
                        'immutability_checkpoints.cold_restarted.after_successful_and_failed_queries.history_event_count',
                        'immutability_checkpoints.cold_restarted.after_successful_and_failed_queries.workflow_command_count',
                        'immutability_checkpoints.completed.before_first_successful_query.history_event_count',
                        'immutability_checkpoints.completed.before_first_successful_query.workflow_command_count',
                        'immutability_checkpoints.completed.answer_before_failed_query',
                        'immutability_checkpoints.completed.failed_query.reason',
                        'immutability_checkpoints.completed.answer_after_failed_query',
                        'immutability_checkpoints.completed.after_successful_and_failed_queries.history_event_count',
                        'immutability_checkpoints.completed.after_successful_and_failed_queries.workflow_command_count',
                        'successful_and_failed_queries_appended_no_history',
                        'successful_and_failed_queries_emitted_no_workflow_commands',
                        'failed_query_did_not_change_later_answer',
                    ],
                ],
                'completed_run_signal_and_query' => [
                    'signal_behavior' => 'typed_terminal_state_error_or_documented_dead_letter',
                    'query_behavior' => 'documented_completed_run_query_behavior',
                    'evidence' => [
                        'completed_run_id',
                        'completed_at',
                        'terminal_status',
                        'signal_api_sample',
                        'signal_error.status_code',
                        'signal_error.reason',
                        'signal_error.rejection_reason',
                        'query_api_sample',
                        'query_result_or_error.status_code',
                        'query_result_or_error.outcome',
                        'signal_error',
                        'query_result_or_error',
                        'public_query_surfaces',
                        'terminal_state_before_operations.history_event_count',
                        'terminal_state_after_operations.history_event_count',
                        'terminal_result_changed_after_operations',
                        'terminal_history_changed_after_operations',
                        'run_status_after_operations',
                    ],
                ],
                'unknown_signal_and_query_errors' => [
                    'required_errors' => [
                        'unknown_signal',
                        'missing_workflow_signal',
                        'missing_workflow_query',
                        'query_not_found',
                        'rejected_unknown_query',
                    ],
                    'evidence' => [
                        'workflow_id',
                        'run_id',
                        'worker_id',
                        'task_queue',
                        'unknown_signal',
                        'missing_workflow_signal',
                        'missing_workflow_query',
                        'query_not_found',
                        'rejected_unknown_query',
                        'known_query_after_unknown_errors',
                        'known_query_after_unknown_expected',
                        'known_query_after_unknown_result',
                        'post_error_query_responder',
                        'history_and_commands_before_rejected_requests.history_event_count',
                        'history_and_commands_before_rejected_requests.workflow_command_count',
                        'history_and_commands_before_rejected_requests.ready_or_leased_workflow_task_count',
                        'history_and_commands_before_rejected_requests.ready_or_leased_workflow_task_set_sha256',
                        'history_and_commands_after_rejected_requests.history_event_count',
                        'history_and_commands_after_rejected_requests.workflow_command_count',
                        'history_and_commands_after_rejected_requests.ready_or_leased_workflow_task_count',
                        'history_and_commands_after_rejected_requests.ready_or_leased_workflow_task_set_sha256',
                        'history_and_commands_after_recovery_query.history_event_count',
                        'history_and_commands_after_recovery_query.workflow_command_count',
                        'history_and_commands_after_recovery_query.ready_or_leased_workflow_task_count',
                        'history_and_commands_after_recovery_query.ready_or_leased_workflow_task_set_sha256',
                        'history_and_commands_after_all_requests.history_event_count',
                        'history_and_commands_after_all_requests.workflow_command_count',
                        'history_and_commands_after_all_requests.ready_or_leased_workflow_task_count',
                        'history_and_commands_after_all_requests.ready_or_leased_workflow_task_set_sha256',
                        'rejected_signal_audit_rows',
                        'rejected_signal_audit_rows_match_expected',
                        'rejected_requests_and_recovery_appended_no_history',
                        'rejected_requests_created_no_executable_or_ready_work',
                        'rejected_signal_handler_invocation_count',
                        'rejected_requests_mutated_no_workflow_state',
                    ],
                    'optional_public_client_error_samples' => [
                        'cli_unknown_signal_sample',
                        'cli_unknown_query_sample',
                        'cli_missing_workflow_signal_sample',
                        'cli_missing_workflow_query_sample',
                        'sdk_python_unknown_signal_sample',
                        'sdk_python_unknown_query_sample',
                        'sdk_python_missing_workflow_signal_sample',
                        'sdk_python_missing_workflow_query_sample',
                    ],
                    'history_integrity' => 'only_exact_rejected_signal_audit_rows_without_executable_work_handler_invocation_or_state_corruption',
                ],
                'malformed_signal_and_query_payloads' => [
                    'required_errors' => [
                        'invalid_signal_arguments',
                        'invalid_query_arguments',
                    ],
                    'evidence' => [
                        'invalid_signal_arguments.status_code',
                        'invalid_signal_arguments.reason',
                        'invalid_query_arguments.status_code',
                        'invalid_query_arguments.reason',
                        'invalid_signal_arguments_context',
                        'invalid_query_arguments_context',
                        'signal_handler_invocation_count_after_invalid_payload',
                        'query_state_mutation_count_after_invalid_payload',
                        'post_error_valid_query_result',
                        'cli_invalid_signal_arguments_sample',
                        'cli_invalid_query_arguments_sample',
                        'sdk_python_invalid_signal_arguments_sample',
                        'sdk_python_invalid_query_arguments_sample',
                    ],
                    'history_integrity' => 'no_handler_invocation_or_state_corruption',
                ],
                'waterline_operator_visibility' => [
                    'required_surfaces' => [
                        'artifact_versions',
                        'artifact_sources',
                        'captured_at',
                        'observer_state.selected_run',
                        'observer_state.signals',
                        'observer_state.queries',
                        'observer_state.paths.selected_run_query_template',
                        'api_paths.selected_run_detail',
                        'api_paths.selected_run_query_action',
                        'dashboard_json_envelopes.selected_run_detail',
                        'api_captures.selected_run_detail',
                        'api_captures.selected_run_query_action',
                        'comparison.run_status_matches_public_clients',
                        'comparison.counter_state_matches_public_clients',
                        'comparison.server_observation',
                        'comparison.cli_observation',
                        'comparison.sdk_observation',
                    ],
                    'allowed_live_query_detail_limitation' => 'query_results_not_materialized_in_selected_run_detail',
                ],
                'waterline_service_operator_visibility' => [
                    'required_surfaces' => [
                        'artifact_versions',
                        'artifact_sources',
                        'captured_at',
                        'probe_started_at',
                        'distribution_identity',
                        'image_reference',
                        'manifest_digest',
                        'source_revision_labels.oci_revision',
                        'source_revision_labels.release_tag',
                        'source_revision_labels.labels',
                        'service_mode.backend',
                        'service_mode.transport',
                        'service_mode.namespace',
                        'service_mode.access_mode',
                        'api_paths.up',
                        'api_paths.running_runs',
                        'api_paths.selected_run_detail',
                        'api_paths.selected_run_query_action',
                        'api_paths.selected_run_signal_action',
                        'api_captures.up.status_code',
                        'api_captures.running_runs.selected_run_present',
                        'api_captures.selected_run_detail',
                        'api_captures.selected_run_query_action',
                        'api_captures.selected_run_signal_action',
                        'comparison.run_identity_matches_public_clients',
                        'comparison.counter_state_matches_public_clients',
                        'comparison.service_mode_uses_public_php_sdk',
                        'comparison.server_observation',
                        'comparison.waterline_service_observation',
                        'query_responder',
                        'query_responder.captured_at',
                        'query_responder.expected_query_identity',
                        'query_responder.designated_target',
                        'query_responder.designated_target.responder_liveness.eligible',
                        'query_responder.query_identity.workflow_id',
                        'query_responder.query_identity.run_id',
                        'query_responder.query_identity.query_name',
                        'query_responder.query_identity.task_queue',
                        'query_responder.query_identity.worker_id',
                        'query_responder.query_identity.query_task_id',
                        'query_responder.query_identity.query_task_attempt',
                        'query_responder.claim_binding.matches_expected',
                        'query_responder.completion_binding.request.query_task_id',
                        'query_responder.completion_binding.request.query_task_attempt',
                        'query_responder.completion_binding.request.lease_owner',
                        'query_responder.completion_binding.response.query_task_id',
                        'query_responder.completion_binding.response.query_task_attempt',
                        'query_responder.completion_binding.response.outcome',
                        'query_responder.completion_binding.authoritative',
                        'query_responder.authoritative_completion',
                        'query_responder.responder_liveness_at_claim.eligible',
                        'query_responder.query_started_at',
                        'query_responder.query_finished_at',
                        'query_responder.responder_started_at',
                        'query_responder.query_claimed_at',
                        'query_responder.completion_request_started_at',
                        'query_responder.completion_recorded_at',
                        'query_responder.responder_finished_at',
                        'query_responder.wait_finished_at',
                    ],
                    'image_policy' => [
                        'environment_variable' => 'DW_WATERLINE_SERVICE_IMAGE',
                        'repository' => 'docker.io/durableworkflow/waterline',
                        'reference_requirement' => 'sha256_digest_only',
                        'tag_only_rejected' => true,
                        'local_source_rejected' => true,
                        'version_source' => 'artifactVersions.waterline',
                        'distribution_identity' => 'waterline-service',
                    ],
                ],
            ],
            'coverage_gate' => [
                'passing_outcome_requires' => [
                    'all_required_scenarios_reported',
                    'all_required_runtimes_present',
                    'all_five_rust_scenarios_report_pass_for_a_tuple_with_sdk_rust',
                    'same_language_cells_reported',
                    'cross_language_cells_reported',
                    'replay_timing_reported',
                    'terminal_run_behavior_reported',
                    'adversarial_errors_typed',
                    'waterline_observer_comparison_reported',
                    'both_waterline_distributions_executed',
                    'artifact_versions_match_latest_published_set',
                    'published_artifact_sources_match_expected_channels',
                    'published_artifact_install_only_includes_per_artifact_install_proof',
                    'python_worker_baseline_identifies_a_published_python_sdk_worker',
                    'rust_cells_identify_the_exact_crates_io_sdk_and_registry_checksum',
                    'rust_avro_cell_executes_a_valid_cross_language_round_trip',
                    'rust_query_immutability_baselines_precede_the_first_successful_query',
                    'rust_snapshot_and_replayed_instance_state_evidence_remain_distinct',
                    'no_local_product_source_artifacts',
                    'findings_linked_for_non_pass_scenarios',
                    'omitted_required_scenarios_link_findings',
                ],
                'uncovered_required_scenario_outcome' => 'non_passing',
                'smoke_subset_outcome' => 'non_passing',
                'unsupported_public_surface_outcome' => 'non_passing_with_root_cause_finding',
                'runner_blocked_outcome' => 'non_passing_runner_blocked',
            ],
            'host_runner_contract' => [
                'status' => 'required_for_passing_signal_query_conformance',
                'runner_repository' => 'server',
                'runner_path' => 'scripts/conformance/signals-queries-published-artifacts.sh',
                'runner_command' => 'scripts/conformance/signals-queries-published-artifacts.sh --result-dir <result-dir>',
                'result_schema' => self::RESULT_SCHEMA,
                'focused_cells' => [
                    'php_worker_cli_signal' => [
                        'status' => 'diagnostic_only',
                        'runner_command' => 'scripts/conformance/signals-queries-published-artifacts.sh --focus=php-worker-cli-signal --result-dir <result-dir>',
                        'result_schema' => 'durable-workflow.v2.signal-query-runtime.php-cli-signal-focused-result',
                        'result_files' => [
                            'signals-queries-php-cli-signal-result.json',
                            'signals-queries-php-cli-signal-record.json',
                        ],
                        'published_artifacts' => [
                            'server',
                            'cli',
                            'sdk-php',
                            'workflow',
                        ],
                        'required_path' => [
                            'php_worker_start',
                            'php_sdk_workflow_start',
                            'cli_initial_query_zero',
                            'cli_signal_increment',
                        ],
                        'required_failed_attempt_evidence' => [
                            'operation_surface',
                            'operation_name',
                            'workflow_identity',
                            'command',
                            'exit_code',
                            'status_code',
                            'reason',
                            'stdout_tail',
                            'stderr_tail',
                            'post_attempt_state.workflow',
                            'post_attempt_state.worker',
                            'post_attempt_state.worker_process',
                            'classification',
                        ],
                        'failure_text_policy' => 'bounded_sanitized_head_and_tail_without_replacing_routing_fields',
                        'broad_property_claimed' => false,
                    ],
                ],
                'portable_result_contract' => [
                    'schema' => 'durable-workflow.v1.portable-native-evidence',
                    'runner_max_bytes' => 1024 * 1024,
                    'host_consumer_max_bytes' => 4 * 1024 * 1024,
                    'required_top_level_fields' => [
                        'schema',
                        'started_at',
                        'finished_at',
                        'outcome',
                        'runner_blocked',
                        'artifactVersions',
                        'executed_distribution_identities',
                        'runtime_matrix',
                        'scenario_results',
                        'findings',
                        'finding_links',
                    ],
                    'scenario_evidence_source' => 'scenario_requirements.*.evidence',
                    'required_scenario_status_source' => 'required_scenarios',
                    'exact_distribution_identity_field' => 'executed_distribution_identities',
                    'native_evidence_failure_classification' => [
                        'oversized' => 'runner_infrastructure_failure',
                        'malformed' => 'runner_infrastructure_failure',
                        'incomplete' => 'runner_infrastructure_failure',
                    ],
                    'product_assertions' => 'fail_closed_before_projection',
                    'sensitive_values' => 'omitted',
                    'unbounded_payloads' => 'sha256_summary_without_payload_bytes',
                ],
                'result_files' => [
                    'pins.json',
                    'run-metadata.json',
                    'signals-queries-result.json',
                    'signals-queries-record.json',
                    'signals-queries-findings.json',
                ],
                'must_execute_against_published_artifacts' => true,
                'must_record_runner_blocked_false_for_product_evidence' => true,
                'must_emit_focused_findings_for_uncovered_cells' => true,
                'required_host_commands' => [
                    'bash',
                    'python3',
                    'docker',
                    'sh',
                ],
                'adversarial_probe_overrides' => [
                    'DW_SIGNALS_QUERIES_RUN_BASELINE_PROBE',
                    'DW_SIGNALS_QUERIES_RUN_ADVERSARIAL_PROBE',
                    'DW_SIGNALS_QUERIES_SERVER_URL',
                    'DW_SIGNALS_QUERIES_SERVER_READY_TIMEOUT_SECONDS',
                    'DW_SIGNALS_QUERIES_AUTH_TOKEN',
                    'DW_SIGNALS_QUERIES_NAMESPACE',
                    'DW_SIGNALS_QUERIES_CLI_BIN',
                    'DW_SIGNALS_QUERIES_PYTHON',
                    'DW_RUST_SDK_VERSION',
                    'DW_SIGNALS_QUERIES_RUST_DOCKER_IMAGE',
                    'DW_SIGNALS_QUERIES_RUN_RUST_MATRIX_PROBE',
                    'DW_WATERLINE_SERVICE_IMAGE',
                    'DW_SIGNALS_QUERIES_RUN_WATERLINE_SERVICE_PROBE',
                    'DW_SIGNALS_QUERIES_KEEP_RUN_ROOT',
                ],
                'required_execution_scopes' => [
                    'published_artifact_install',
                    'python_worker_cli_and_sdk_smoke',
                    'php_worker_mirror',
                    'cross_language_client_matrix',
                    'rust_published_artifact_matrix',
                    'ordered_signal_delivery',
                    'dedup_contract_observation',
                    'replay_timing',
                    'completed_run_handling',
                    'unknown_handler_errors',
                    'malformed_payload_errors',
                    'waterline_observer_comparison',
                    'waterline_service_observer_comparison',
                ],
                'baseline_probe_not_claimed_as_pass' => [],
                'evidence_shards' => [
                    'published_artifact_install' => [
                        'must_cover_scenarios' => [
                            'published_artifact_install_only',
                        ],
                        'current_evidence_fields' => [
                            'published_artifact_versions',
                            'artifact_sources',
                            'artifact_install_evidence',
                            'external_smoke_evidence',
                        ],
                        'expected_artifact_sources' => [
                            'server' => 'published_docker_image',
                            'cli' => 'published_cli_release',
                            'sdk-php' => 'published_composer_package',
                            'sdk-python' => 'published_pypi_package',
                            'sdk-rust' => 'published_crates_io_package',
                            'workflow' => 'published_composer_package',
                            'waterline' => 'published_waterline_artifact',
                        ],
                        'install_proof_artifacts' => [
                            'server',
                            'cli',
                            'sdk-php',
                            'sdk-python',
                            'sdk-rust',
                        ],
                        'baseline_probe_claims_pass' => true,
                        'pass_claim_source' => 'published_artifact_install_probe',
                        'finding_type_when_missing' => 'signal_query_published_artifact_install_uncovered',
                        'owning_surface' => 'conformance_harness',
                    ],
                    'python_worker_cli_and_sdk_smoke' => [
                        'must_cover_scenarios' => [
                            'python_worker_cli_and_sdk_baseline',
                        ],
                        'current_evidence_fields' => [
                            'worker_runtime',
                            'python_worker_artifact_source',
                            'python_worker_sdk_version',
                            'python_worker_query_task_routing',
                            'routed_current_query_task',
                            'cli_signal_and_query',
                            'sdk_python_signal_and_query',
                            'immediate_repeat_query_consistency',
                            'readiness_boundary',
                            'controlled_restart',
                        ],
                        'baseline_probe_claims_pass' => true,
                        'pass_claim_source' => 'published_python_sdk_worker_baseline_probe',
                        'finding_type_when_missing' => 'signal_query_python_smoke_uncovered',
                        'finding_type_when_product_behavior_fails' => 'signal_query_python_baseline_failed',
                        'finding_type_when_routed_current_query_missing' => 'signal_query_python_routed_current_query_evidence_missing',
                        'owning_surface' => 'sdk-python, cli, server',
                    ],
                    'ordered_signal_delivery' => [
                        'must_cover_scenarios' => [
                            'ordered_signal_delivery',
                        ],
                        'current_evidence_fields' => [
                            'workflow_id',
                            'run_id',
                            'rapid_increment_inputs',
                            'accepted_signal_inputs',
                            'accepted_signal_total',
                            'queried_total',
                            'history_signal_order',
                            'final_run_status',
                            'ordered_query_responder',
                        ],
                        'finding_type_when_missing' => 'signal_query_ordered_delivery_uncovered',
                        'owning_surface' => 'server',
                    ],
                    'dedup_contract_observation' => [
                        'must_cover_scenarios' => [
                            'dedup_contract_observation',
                        ],
                        'required_evidence_fields' => [
                            'client_side_key_support',
                            'documented_contract',
                            'handler_observation_count',
                        ],
                        'finding_type_when_missing' => 'signal_query_dedup_contract_uncovered',
                        'owning_surface' => 'server, sdk-python, workflow, cli, docs',
                    ],
                    'php_worker_mirror' => [
                        'must_cover_scenarios' => [
                            'php_worker_cli_and_sdk_baseline',
                        ],
                        'required_evidence_fields' => [
                            'worker_runtime',
                            'sdk_php_artifact_source',
                            'sdk_php_sdk_version',
                            'php_worker_query_task_routing',
                            'routed_current_query_task',
                            'cli_signal_and_query',
                            'sdk_php_signal_and_query',
                            'immediate_repeat_query_consistency',
                        ],
                        'finding_type_when_missing' => 'signal_query_php_worker_mirror_uncovered',
                        'finding_type_when_product_behavior_fails' => 'signal_query_php_worker_mirror_failed',
                        'retained_failure_diagnostics' => [
                            'failure_code' => 'php_worker_mirror_probe_failed',
                            'source_field' => 'current_behavior_failures[].actual',
                            'result_field' => 'behavior_failure_diagnostics.php_worker_cli_and_sdk_baseline.current_behavior_failures[].actual',
                            'record_field' => 'behavior_failure_diagnostics.php_worker_cli_and_sdk_baseline.current_behavior_failures[].actual',
                            'stdout_field' => 'behavior_failure_diagnostics.php_worker_cli_and_sdk_baseline.current_behavior_failures[].actual',
                            'actual_payload_fields' => [
                                'probe_error',
                                'worker_registration',
                                'sdk_php_start',
                                'initial_query',
                                'cli_signal',
                                'cli_signal_attempt_classification',
                                'post_cli_signal_state',
                                'cli_query',
                                'sdk_php_signal',
                                'sdk_php_query',
                                'repeat_query',
                            ],
                        ],
                        'owning_surface' => 'workflow',
                    ],
                    'cross_language_client_matrix' => [
                        'must_cover_scenarios' => [
                            'python_worker_php_facing_and_cli_clients',
                            'php_worker_python_and_cli_clients',
                        ],
                        'required_evidence_fields' => [
                            'php_client_signal_and_query',
                            'sdk_python_signal_and_query',
                            'cli_signal_and_query',
                            'cross_language_query_consistency',
                            'wire_envelope_compatibility',
                        ],
                        'finding_type_when_missing' => 'signal_query_cross_language_client_matrix_uncovered',
                        'owning_surface' => 'workflow, sdk-python, cli',
                    ],
                    'rust_published_artifact_matrix' => [
                        'must_cover_scenarios' => [
                            'rust_worker_rust_php_python_clients',
                            'python_worker_rust_client',
                            'php_worker_rust_client',
                            'rust_query_error_and_immutability',
                            'rust_replayed_instance_state_query_after_cold_restart',
                        ],
                        'crate' => [
                            'package' => 'durable-workflow',
                            'source' => 'crates.io',
                            'version_source' => 'artifactVersions.sdk-rust',
                            'cargo_requirement_template' => '={version}',
                            'requires_exact_semver' => true,
                        ],
                        'query_state_models' => [
                            'rust_worker_rust_php_python_clients' => 'snapshot_derived_transport_state',
                            'rust_query_error_and_immutability' => 'snapshot_derived_transport_state',
                            'rust_replayed_instance_state_query_after_cold_restart' => 'replayed_workflow_instance_state',
                        ],
                        'finding_type_when_missing' => 'signal_query_rust_published_artifact_matrix_uncovered',
                        'owning_surface' => 'sdk-rust, workflow, sdk-python, server',
                    ],
                    'replay_timing' => [
                        'must_cover_scenarios' => [
                            'signal_during_replay',
                            'query_during_replay',
                        ],
                        'required_evidence_fields' => [
                            'signal_api_sample',
                            'signal_status_code',
                            'worker_restart_at',
                            'signal_sent_at',
                            'replay_completed_at',
                            'signal_applied_at',
                            'query_api_sample',
                            'query_status_code',
                            'query_sent_at',
                            'query_poll_started_at',
                            'query_handler_invoked_at',
                            'query_completed_at',
                            'query_answer',
                            'expected_answer',
                        ],
                        'finding_type_when_missing' => 'signal_query_replay_timing_uncovered',
                        'owning_surface' => 'workflow, sdk-python',
                    ],
                    'completed_run_handling' => [
                        'must_cover_scenarios' => [
                            'completed_run_signal_and_query',
                        ],
                        'required_evidence_fields' => [
                            'completed_run_id',
                            'completed_at',
                            'terminal_status',
                            'signal_api_sample',
                            'signal_error.status_code',
                            'signal_error.reason',
                            'signal_error.rejection_reason',
                            'query_api_sample',
                            'query_result_or_error.status_code',
                            'query_result_or_error.outcome',
                            'signal_error',
                            'query_result_or_error',
                            'public_query_surfaces',
                            'terminal_state_before_operations.history_event_count',
                            'terminal_state_after_operations.history_event_count',
                            'terminal_result_changed_after_operations',
                            'terminal_history_changed_after_operations',
                            'run_status_after_operations',
                        ],
                        'finding_type_when_missing' => 'signal_query_completed_run_handling_uncovered',
                        'finding_type_when_product_behavior_fails' => 'signal_query_completed_run_handling_failed',
                        'finding_type_when_probe_unavailable' => 'signal_query_completed_run_probe_unavailable',
                        'owning_surface' => 'server, workflow, sdk-python, cli',
                    ],
                    'unknown_handler_errors' => [
                        'must_cover_scenarios' => [
                            'unknown_signal_and_query_errors',
                        ],
                        'required_evidence_fields' => [
                            'workflow_id',
                            'run_id',
                            'worker_id',
                            'task_queue',
                            'unknown_signal',
                            'missing_workflow_signal',
                            'missing_workflow_query',
                            'query_not_found',
                            'rejected_unknown_query',
                            'known_query_after_unknown_errors',
                            'known_query_after_unknown_expected',
                            'known_query_after_unknown_result',
                            'post_error_query_responder',
                            'history_and_commands_before_rejected_requests.history_event_count',
                            'history_and_commands_before_rejected_requests.workflow_command_count',
                            'history_and_commands_before_rejected_requests.ready_or_leased_workflow_task_count',
                            'history_and_commands_before_rejected_requests.ready_or_leased_workflow_task_set_sha256',
                            'history_and_commands_after_rejected_requests.history_event_count',
                            'history_and_commands_after_rejected_requests.workflow_command_count',
                            'history_and_commands_after_rejected_requests.ready_or_leased_workflow_task_count',
                            'history_and_commands_after_rejected_requests.ready_or_leased_workflow_task_set_sha256',
                            'history_and_commands_after_recovery_query.history_event_count',
                            'history_and_commands_after_recovery_query.workflow_command_count',
                            'history_and_commands_after_recovery_query.ready_or_leased_workflow_task_count',
                            'history_and_commands_after_recovery_query.ready_or_leased_workflow_task_set_sha256',
                            'history_and_commands_after_all_requests.history_event_count',
                            'history_and_commands_after_all_requests.workflow_command_count',
                            'history_and_commands_after_all_requests.ready_or_leased_workflow_task_count',
                            'history_and_commands_after_all_requests.ready_or_leased_workflow_task_set_sha256',
                            'rejected_signal_audit_rows',
                            'rejected_signal_audit_rows_match_expected',
                            'rejected_requests_and_recovery_appended_no_history',
                            'rejected_requests_created_no_executable_or_ready_work',
                            'rejected_signal_handler_invocation_count',
                            'rejected_requests_mutated_no_workflow_state',
                        ],
                        'optional_evidence_fields' => [
                            'cli_unknown_signal_sample',
                            'cli_unknown_query_sample',
                            'cli_missing_workflow_signal_sample',
                            'cli_missing_workflow_query_sample',
                            'sdk_python_unknown_signal_sample',
                            'sdk_python_unknown_query_sample',
                            'sdk_python_missing_workflow_signal_sample',
                            'sdk_python_missing_workflow_query_sample',
                        ],
                        'finding_type_when_missing' => 'signal_query_unknown_handler_errors_uncovered',
                        'owning_surface' => 'server, workflow, sdk-python, cli',
                    ],
                    'malformed_payload_errors' => [
                        'must_cover_scenarios' => [
                            'malformed_signal_and_query_payloads',
                        ],
                        'required_evidence_fields' => [
                            'invalid_signal_arguments',
                            'invalid_query_arguments',
                            'invalid_signal_arguments.status_code',
                            'invalid_signal_arguments.reason',
                            'invalid_query_arguments.status_code',
                            'invalid_query_arguments.reason',
                            'invalid_signal_arguments_context',
                            'invalid_query_arguments_context',
                            'signal_handler_invocation_count_after_invalid_payload',
                            'query_state_mutation_count_after_invalid_payload',
                            'post_error_valid_query_result',
                            'cli_invalid_signal_arguments_sample',
                            'cli_invalid_query_arguments_sample',
                            'sdk_python_invalid_signal_arguments_sample',
                            'sdk_python_invalid_query_arguments_sample',
                        ],
                        'finding_type_when_missing' => 'signal_query_adversarial_error_shapes_uncovered',
                        'owning_surface' => 'server, workflow, sdk-python, cli',
                    ],
                    'waterline_observer_comparison' => [
                        'must_cover_scenarios' => [
                            'waterline_operator_visibility',
                        ],
                        'required_evidence_fields' => [
                            'artifact_versions',
                            'artifact_sources',
                            'captured_at',
                            'observer_state.selected_run',
                            'observer_state.signals',
                            'observer_state.queries',
                            'observer_state.paths.selected_run_query_template',
                            'api_paths.selected_run_detail',
                            'api_paths.selected_run_query_action',
                            'dashboard_json_envelopes.selected_run_detail',
                            'api_captures.selected_run_detail',
                            'api_captures.selected_run_query_action',
                            'comparison.run_status_matches_public_clients',
                            'comparison.counter_state_matches_public_clients',
                            'comparison.server_observation',
                            'comparison.cli_observation',
                            'comparison.sdk_observation',
                        ],
                        'finding_type_when_missing' => 'signal_query_waterline_observer_comparison_uncovered',
                        'owning_surface' => 'waterline',
                    ],
                    'waterline_service_observer_comparison' => [
                        'must_cover_scenarios' => [
                            'waterline_service_operator_visibility',
                        ],
                        'required_evidence_fields' => [
                            'artifact_versions',
                            'artifact_sources',
                            'captured_at',
                            'probe_started_at',
                            'distribution_identity',
                            'image_reference',
                            'manifest_digest',
                            'source_revision_labels.oci_revision',
                            'source_revision_labels.release_tag',
                            'source_revision_labels.labels',
                            'service_mode.backend',
                            'service_mode.transport',
                            'service_mode.namespace',
                            'service_mode.access_mode',
                            'api_paths.up',
                            'api_paths.running_runs',
                            'api_paths.selected_run_detail',
                            'api_paths.selected_run_query_action',
                            'api_paths.selected_run_signal_action',
                            'api_captures.up.status_code',
                            'api_captures.running_runs.selected_run_present',
                            'api_captures.selected_run_detail',
                            'api_captures.selected_run_query_action',
                            'api_captures.selected_run_signal_action',
                            'comparison.run_identity_matches_public_clients',
                            'comparison.counter_state_matches_public_clients',
                            'comparison.service_mode_uses_public_php_sdk',
                            'comparison.server_observation',
                            'comparison.waterline_service_observation',
                            'query_responder',
                            'query_responder.captured_at',
                            'query_responder.expected_query_identity',
                            'query_responder.designated_target',
                            'query_responder.designated_target.responder_liveness.eligible',
                            'query_responder.query_identity.workflow_id',
                            'query_responder.query_identity.run_id',
                            'query_responder.query_identity.query_name',
                            'query_responder.query_identity.task_queue',
                            'query_responder.query_identity.worker_id',
                            'query_responder.query_identity.query_task_id',
                            'query_responder.query_identity.query_task_attempt',
                            'query_responder.claim_binding.matches_expected',
                            'query_responder.completion_binding.request.query_task_id',
                            'query_responder.completion_binding.request.query_task_attempt',
                            'query_responder.completion_binding.request.lease_owner',
                            'query_responder.completion_binding.response.query_task_id',
                            'query_responder.completion_binding.response.query_task_attempt',
                            'query_responder.completion_binding.response.outcome',
                            'query_responder.completion_binding.authoritative',
                            'query_responder.authoritative_completion',
                            'query_responder.responder_liveness_at_claim.eligible',
                            'query_responder.query_started_at',
                            'query_responder.query_finished_at',
                            'query_responder.responder_started_at',
                            'query_responder.query_claimed_at',
                            'query_responder.completion_request_started_at',
                            'query_responder.completion_recorded_at',
                            'query_responder.responder_finished_at',
                            'query_responder.wait_finished_at',
                        ],
                        'image_reference_source' => 'DW_WATERLINE_SERVICE_IMAGE',
                        'requires_digest_reference' => true,
                        'required_distribution_identity' => 'waterline-service',
                        'version_source' => 'artifactVersions.waterline',
                        'finding_type_when_missing' => 'signal_query_waterline_service_observer_uncovered',
                        'owning_surface' => 'waterline',
                    ],
                ],
                'routing_policy' => [
                    'missing_required_scenario' => [
                        'result_status' => 'not_covered',
                        'finding_type' => 'conformance_runner_coverage_gap',
                        'owner' => 'conformance_harness',
                    ],
                    'product_behavior_failure' => [
                        'result_status' => 'fail',
                        'finding_type' => 'product_contract_failure',
                        'owner' => 'owning_surface_from_finding_policy',
                    ],
                    'unsupported_public_surface' => [
                        'result_status' => 'unsupported',
                        'finding_type' => 'unsupported_public_surface',
                        'owner' => 'owning_surface_from_evidence_shard',
                    ],
                ],
            ],
            'result_gate' => SignalQueryRuntimeResultGate::spec(),
            'finding_policy' => [
                'ordering_drift' => 'link_root_cause_finding_against_server',
                'query_staleness' => 'link_root_cause_finding_against_owning_sdk_or_runtime',
                'terminal_run_mismatch' => 'link_root_cause_finding_against_server_or_documentation_owner',
                'malformed_payload_acceptance' => 'link_root_cause_finding_against_emitting_surface',
                'runtime_asymmetry' => 'link_root_cause_finding_against_asymmetric_runtime',
                'observer_mismatch' => 'link_root_cause_finding_against_waterline',
                'unsupported_public_surface' => 'link_root_cause_finding_against_surface_owner',
            ],
        ];
    }
}
